sonar.projectKey=devsecops-production-pipeline
sonar.projectName=DevSecOps Production Pipeline

sonar.sources=backend,frontend,nginx
sonar.exclusions=**/__pycache__/**,**/*.pyc

sonar.sourceEncoding=UTF-8
